# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mac Bellingrath | iOS Developer
email: hello@macbellingrath.com
description: > 
Mac Bellingrath | iOS Developer:
baseurl: ""
url: "http://macbellingrath.com" # the base hostname & protocol for your site
twitter_username: mbellingrath
github_username:  macbellingrath
highlighter: rouge 

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:         _sass
  style:            :compressed


# Build settings
markdown: kramdown
#Gems
gems: [jekyll-paginate]

paginate: 3
paginate_path: "blog/page:num/"
theme: jekyll-theme-minimal